spring:
  profiles:
    group: # Run - Edit Configurations - Active Profiles에서 [profile name] 설정
      dev: common, dev
      prod: common, prod
  datasource:
    #mysql 8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://158.180.89.135:3306/Book_Loan_System
    username: hjlee
    password: Oracle123456789!
  sql:
    init:
      platform: mysql
---

# 공통 설정
spring:
  config:
    activate:
      on-profile: common
  application:
    name: BookLoanSystem
  # mvc Settings
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**


# HTTP Encoding Settings
server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MyBatis 설정
mybatis:
  # resources/mapper/*.xml
  mapper-locations: mybatis/mapper/*.xml

---


# dev 프로필 데이터베이스 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    #mysql 8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://158.180.89.135:3306/Book_Loan_System
    username: hjlee
    password: Oracle123456789!
  sql:
    init:
      platform: mysql
---

# prod 프로필 Oracle 데이터베이스 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: final
    password: final
  sql:
    init:
      platform: oracle

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      # create, update, create-drop, none 등의 옵션이 있습니다.
      # create: 기존테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      # create-drop: create와 같으나 종료 시점에 테이블 DROP
      # none: 사용하지 않음
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # DDl 생성 시 데이터베이스 고유의 기능 사용여부
    generate-ddl: false
    # 실행되는 쿼리문 보여주기 여부
    show-sql: false
    properties:
      hibernate:
        format_sql: false

---

